In [86]:
from google.colab import drive
drive.mount("/content/drive", force_remount=True)

Mounted at /content/drive

In [87]:
import pandas as pd
import numpy as np
data = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_trip.csv")
data

,EVENT_NO_TRIP,EVENT_NO_STOP,OPD_DATE,VEHICLE_ID,METERS,ACT_TIME,GPS_LONGITUDE,GPS_LATITUDE,GPS_SATELLITES,GPS_HDOP
0,259172515,259172517,15FEB2023:00:00:00,4223,40,20469,-122.648137,45.493082,12,0.7
1,259172515,259172517,15FEB2023:00:00:00,4223,48,20474,-122.648240,45.493070,12,0.8
2,259172515,259172517,15FEB2023:00:00:00,4223,57,20479,-122.648352,45.493123,12,0.8
3,259172515,259172517,15FEB2023:00:00:00,4223,73,20484,-122.648385,45.493262,12,0.7
4,259172515,259172517,15FEB2023:00:00:00,4223,112,20489,-122.648347,45.493582,12,0.8
...,...,...,...,...,...,...,...,...,...,...
156,259172515,259172530,15FEB2023:00:00:00,4223,5834,21389,-122.677057,45.528040,11,0.8
157,259172515,259172531,15FEB2023:00:00:00,4223,5838,21424,-122.677003,45.528037,6,2.0
158,259172515,259172531,15FEB2023:00:00:00,4223,5858,21429,-122.676765,45.528043,7,1.1
159,259172515,259172531,15FEB2023:00:00:00,4223,5889,21434,-122.676370,45.528047,10,1.1
160,259172515,259172531,15FEB2023:00:00:00,4223,5918,21439,-122.675990,45.528065,11,0.8

In [88]:
dropped_data = data.drop(columns=['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP'])
dropped_data

,EVENT_NO_TRIP,OPD_DATE,VEHICLE_ID,METERS,ACT_TIME,GPS_LONGITUDE,GPS_LATITUDE
0,259172515,15FEB2023:00:00:00,4223,40,20469,-122.648137,45.493082
1,259172515,15FEB2023:00:00:00,4223,48,20474,-122.648240,45.493070
2,259172515,15FEB2023:00:00:00,4223,57,20479,-122.648352,45.493123
3,259172515,15FEB2023:00:00:00,4223,73,20484,-122.648385,45.493262
4,259172515,15FEB2023:00:00:00,4223,112,20489,-122.648347,45.493582
...,...,...,...,...,...,...,...
156,259172515,15FEB2023:00:00:00,4223,5834,21389,-122.677057,45.528040
157,259172515,15FEB2023:00:00:00,4223,5838,21424,-122.677003,45.528037
158,259172515,15FEB2023:00:00:00,4223,5858,21429,-122.676765,45.528043
159,259172515,15FEB2023:00:00:00,4223,5889,21434,-122.676370,45.528047
160,259172515,15FEB2023:00:00:00,4223,5918,21439,-122.675990,45.528065

In [89]:
exclude_columns = ['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP']

all_columns = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_trip.csv",nrows=0).columns.tolist()

use_columns = [col for col in all_columns if col not in exclude_columns]

df = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_trip.csv", usecols=use_columns)
df

,EVENT_NO_TRIP,OPD_DATE,VEHICLE_ID,METERS,ACT_TIME,GPS_LONGITUDE,GPS_LATITUDE
0,259172515,15FEB2023:00:00:00,4223,40,20469,-122.648137,45.493082
1,259172515,15FEB2023:00:00:00,4223,48,20474,-122.648240,45.493070
2,259172515,15FEB2023:00:00:00,4223,57,20479,-122.648352,45.493123
3,259172515,15FEB2023:00:00:00,4223,73,20484,-122.648385,45.493262
4,259172515,15FEB2023:00:00:00,4223,112,20489,-122.648347,45.493582
...,...,...,...,...,...,...,...
156,259172515,15FEB2023:00:00:00,4223,5834,21389,-122.677057,45.528040
157,259172515,15FEB2023:00:00:00,4223,5838,21424,-122.677003,45.528037
158,259172515,15FEB2023:00:00:00,4223,5858,21429,-122.676765,45.528043
159,259172515,15FEB2023:00:00:00,4223,5889,21434,-122.676370,45.528047
160,259172515,15FEB2023:00:00:00,4223,5918,21439,-122.675990,45.528065

In [90]:
from datetime import datetime, timedelta

def decode_timestamp(opd_date, act_time):
    date_time = datetime.strptime(opd_date, "%d%b%Y:%H:%M:%S")
    time_delta = timedelta(seconds=act_time)
    return date_time + time_delta

df['TIMESTAMP'] = df.apply(lambda row: decode_timestamp(row['OPD_DATE'], row['ACT_TIME']), axis=1)
df

,EVENT_NO_TRIP,OPD_DATE,VEHICLE_ID,METERS,ACT_TIME,GPS_LONGITUDE,GPS_LATITUDE,TIMESTAMP
0,259172515,15FEB2023:00:00:00,4223,40,20469,-122.648137,45.493082,2023-02-15 05:41:09
1,259172515,15FEB2023:00:00:00,4223,48,20474,-122.648240,45.493070,2023-02-15 05:41:14
2,259172515,15FEB2023:00:00:00,4223,57,20479,-122.648352,45.493123,2023-02-15 05:41:19
3,259172515,15FEB2023:00:00:00,4223,73,20484,-122.648385,45.493262,2023-02-15 05:41:24
4,259172515,15FEB2023:00:00:00,4223,112,20489,-122.648347,45.493582,2023-02-15 05:41:29
...,...,...,...,...,...,...,...,...
156,259172515,15FEB2023:00:00:00,4223,5834,21389,-122.677057,45.528040,2023-02-15 05:56:29
157,259172515,15FEB2023:00:00:00,4223,5838,21424,-122.677003,45.528037,2023-02-15 05:57:04
158,259172515,15FEB2023:00:00:00,4223,5858,21429,-122.676765,45.528043,2023-02-15 05:57:09
159,259172515,15FEB2023:00:00:00,4223,5889,21434,-122.676370,45.528047,2023-02-15 05:57:14
160,259172515,15FEB2023:00:00:00,4223,5918,21439,-122.675990,45.528065,2023-02-15 05:57:19

In [91]:
df_timestamp = df.drop(columns=['OPD_DATE', 'ACT_TIME'])
df_timestamp

,EVENT_NO_TRIP,VEHICLE_ID,METERS,GPS_LONGITUDE,GPS_LATITUDE,TIMESTAMP
0,259172515,4223,40,-122.648137,45.493082,2023-02-15 05:41:09
1,259172515,4223,48,-122.648240,45.493070,2023-02-15 05:41:14
2,259172515,4223,57,-122.648352,45.493123,2023-02-15 05:41:19
3,259172515,4223,73,-122.648385,45.493262,2023-02-15 05:41:24
4,259172515,4223,112,-122.648347,45.493582,2023-02-15 05:41:29
...,...,...,...,...,...,...
156,259172515,4223,5834,-122.677057,45.528040,2023-02-15 05:56:29
157,259172515,4223,5838,-122.677003,45.528037,2023-02-15 05:57:04
158,259172515,4223,5858,-122.676765,45.528043,2023-02-15 05:57:09
159,259172515,4223,5889,-122.676370,45.528047,2023-02-15 05:57:14
160,259172515,4223,5918,-122.675990,45.528065,2023-02-15 05:57:19

In [92]:

df_timestamp['dMETERS'] = df_timestamp['METERS'].diff()
df_timestamp['dTIMESTAMP'] = df_timestamp['TIMESTAMP'].diff().dt.total_seconds()

df_timestamp['SPEED'] = df_timestamp.apply(
    lambda row: row['dMETERS'] / row['dTIMESTAMP'] if row['dTIMESTAMP'] != 0 else 0,
    axis=1
)
df_timestamp.iloc[0, df_timestamp.columns.get_loc('SPEED')] = df_timestamp.iloc[1]['SPEED']

df_timestamp.drop(['dMETERS', 'dTIMESTAMP'], axis=1, inplace=True)


df_timestamp

,EVENT_NO_TRIP,VEHICLE_ID,METERS,GPS_LONGITUDE,GPS_LATITUDE,TIMESTAMP,SPEED
0,259172515,4223,40,-122.648137,45.493082,2023-02-15 05:41:09,1.600000
1,259172515,4223,48,-122.648240,45.493070,2023-02-15 05:41:14,1.600000
2,259172515,4223,57,-122.648352,45.493123,2023-02-15 05:41:19,1.800000
3,259172515,4223,73,-122.648385,45.493262,2023-02-15 05:41:24,3.200000
4,259172515,4223,112,-122.648347,45.493582,2023-02-15 05:41:29,7.800000
...,...,...,...,...,...,...,...
156,259172515,4223,5834,-122.677057,45.528040,2023-02-15 05:56:29,2.800000
157,259172515,4223,5838,-122.677003,45.528037,2023-02-15 05:57:04,0.114286
158,259172515,4223,5858,-122.676765,45.528043,2023-02-15 05:57:09,4.000000
159,259172515,4223,5889,-122.676370,45.528047,2023-02-15 05:57:14,6.200000
160,259172515,4223,5918,-122.675990,45.528065,2023-02-15 05:57:19,5.800000

In [93]:

speed_stats = df_timestamp['SPEED'].describe()
print("Minimum speed:", round(speed_stats['min'], 3), "m/s")
print("Maximum speed:", round(speed_stats['max'], 3), "m/s")
print("Average speed:", round(speed_stats['mean'], 3), "m/s")

Minimum speed: 0.0 m/s
Maximum speed: 17.4 m/s
Average speed: 7.192 m/s

In [130]:

exclude_columns = ['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP']

all_columns = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_veh4223_230215.csv",nrows=0).columns.tolist()

use_columns = [col for col in all_columns if col not in exclude_columns]

df1 = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_veh4223_230215.csv", usecols=use_columns)

trips1 = df1.groupby('EVENT_NO_TRIP')
unique_trips1 = trips1.groups.keys()

full_list = []


for trip in unique_trips1:
    trip_data1 = trips1.get_group(trip).copy()
    # print(trip_data1)
    trip_data1['TIMESTAMP'] = trip_data1.apply(lambda row: decode_timestamp(row['OPD_DATE'], row['ACT_TIME']), axis=1)
    trip_data2 = trip_data1.drop(columns=['OPD_DATE', 'ACT_TIME'])

    trip_data2['dMETERS'] = trip_data2['METERS'].diff()
    trip_data2['dTIMESTAMP'] = trip_data2['TIMESTAMP'].diff().dt.total_seconds()
    trip_data2['SPEED'] = trip_data2.apply(
    lambda row: row['dMETERS'] / row['dTIMESTAMP'] if row['dTIMESTAMP'] != 0 else 0,
    axis=1
)
    if len(trip_data2) > 1:
        trip_data2.iloc[0, trip_data2.columns.get_loc('SPEED')] = trip_data2.iloc[1]['SPEED']
    else:
        trip_data2.iloc[0, trip_data2.columns.get_loc('SPEED')] = 0
    trip_data2.drop(['dMETERS', 'dTIMESTAMP'], axis=1, inplace=True)

The maximum speed for vehicle #4223 on February 15, 2023 is: 17.4

In [134]:

exclude_columns = ['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP']
all_columns = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_veh4223_230215.csv", nrows=0).columns.tolist()
use_columns = [col for col in all_columns if col not in exclude_columns]
df1 = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_veh4223_230215.csv", usecols=use_columns)

trips1 = df1.groupby('EVENT_NO_TRIP')
unique_trips1 = trips1.groups.keys()

max_speed = 0
max_speed_time = None
max_speed_location = None

all_speeds = []

for trip in unique_trips1:
    trip_data = trips1.get_group(trip).copy()
    trip_data['TIMESTAMP'] = trip_data.apply(lambda row: decode_timestamp(row['OPD_DATE'], row['ACT_TIME']), axis=1)
    trip_data = trip_data.drop(columns=['OPD_DATE', 'ACT_TIME'])

    trip_data['dMETERS'] = trip_data['METERS'].diff()
    trip_data['dTIMESTAMP'] = trip_data['TIMESTAMP'].diff().dt.total_seconds()
    trip_data['SPEED'] = trip_data.apply(lambda row: row['dMETERS'] / row['dTIMESTAMP'] if row['dTIMESTAMP'] != 0 else 0, axis=1)
    if len(trip_data) > 1:
        trip_data.iloc[0, trip_data.columns.get_loc('SPEED')] = trip_data.iloc[1]['SPEED']
    else:
        trip_data.iloc[0, trip_data.columns.get_loc('SPEED')] = 0

    trip_data.drop(['dMETERS', 'dTIMESTAMP'], axis=1, inplace=True)
    all_speeds.extend(trip_data['SPEED'].tolist())
    current_max_speed = trip_data['SPEED'].max()
    if current_max_speed > max_speed:
        max_speed = current_max_speed
        max_speed_row = trip_data[trip_data['SPEED'] == max_speed].iloc[0]
        max_speed_time = max_speed_row['TIMESTAMP']
        max_speed_location = (max_speed_row['GPS_LATITUDE'], max_speed_row['GPS_LONGITUDE'])

median_speed = pd.Series(all_speeds).median()

print("Maximum Speed:", max_speed, "m/s")
print("Occurred at:", max_speed_time, "at location", max_speed_location)
print("Median Speed:", median_speed, "m/s")

Maximum Speed: 17.4 m/s
Occurred at: 2023-02-15 05:44:49 at location (45.505452, -122.660822)
Median Speed: 7.2 m/s

In [135]:
import pandas as pd
entire_day_data = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_230215.csv")
entire_day_data

,EVENT_NO_TRIP,EVENT_NO_STOP,OPD_DATE,VEHICLE_ID,METERS,ACT_TIME,GPS_LONGITUDE,GPS_LATITUDE,GPS_SATELLITES,GPS_HDOP
0,259173279,259173350,15FEB2023:00:00:00,4223,194493,71279,-122.679572,45.517122,8.0,1.6
1,259173279,259173350,15FEB2023:00:00:00,4223,194525,71284,-122.679408,45.517392,8.0,1.9
2,259173279,259173350,15FEB2023:00:00:00,4223,194562,71290,-122.679227,45.517700,8.0,2.2
3,259173279,259173350,15FEB2023:00:00:00,4223,194598,71295,-122.679048,45.517998,9.0,0.9
4,259173279,259173350,15FEB2023:00:00:00,4223,194628,71300,-122.678888,45.518255,9.0,1.3
...,...,...,...,...,...,...,...,...,...,...
2221397,258480928,258480932,15FEB2023:00:00:00,4304,109998,69191,-122.686300,45.594515,12.0,1.4
2221398,258480928,258480932,15FEB2023:00:00:00,4304,110041,69197,-122.686768,45.594723,12.0,0.8
2221399,258480928,258480932,15FEB2023:00:00:00,4304,110079,69202,-122.686840,45.595065,12.0,0.8
2221400,258480928,258480932,15FEB2023:00:00:00,4304,110114,69207,-122.686522,45.595262,12.0,0.8
2221401,258480928,258480932,15FEB2023:00:00:00,4304,110160,69211,-122.685990,45.595175,12.0,0.8

In [136]:
import pandas as pd


exclude_columns = ['EVENT_NO_STOP', 'GPS_SATELLITES', 'GPS_HDOP']
all_columns = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_230215.csv", nrows=0).columns.tolist()
use_columns = [col for col in all_columns if col not in exclude_columns]
df2 = pd.read_csv("/content/drive/MyDrive/bc_trip/bc_230215.csv", usecols=use_columns)


trips2 = df2.groupby('EVENT_NO_TRIP')

max_speed = 0
max_speed_details = None

mean_speeds = {}

for trip in trips2.groups.keys():
    trip_data = trips2.get_group(trip).copy()
    trip_data['TIMESTAMP'] = trip_data.apply(lambda row: decode_timestamp(row['OPD_DATE'], row['ACT_TIME']), axis=1)
    trip_data = trip_data.drop(columns=['OPD_DATE', 'ACT_TIME'])

    trip_data['dMETERS'] = trip_data['METERS'].diff()
    trip_data['dTIMESTAMP'] = trip_data['TIMESTAMP'].diff().dt.total_seconds()
    trip_data['SPEED'] = trip_data.apply(lambda row: row['dMETERS'] / row['dTIMESTAMP'] if row['dTIMESTAMP'] != 0 else 0, axis=1)
    if len(trip_data) > 1:
        trip_data.iloc[0, trip_data.columns.get_loc('SPEED')] = trip_data.iloc[1]['SPEED']
    else:
        trip_data.iloc[0, trip_data.columns.get_loc('SPEED')] = 0
    trip_data.drop(['dMETERS', 'dTIMESTAMP'], axis=1, inplace=True)


    mean_speed = trip_data['SPEED'].mean()
    mean_speeds[(trip_data.iloc[0]['VEHICLE_ID'], trip)] = mean_speed


    current_max_speed = trip_data['SPEED'].max()
    if current_max_speed > max_speed:
        max_speed = current_max_speed
        max_speed_row = trip_data[trip_data['SPEED'] == max_speed].iloc[0]
        max_speed_details = {
            'time': max_speed_row['TIMESTAMP'],
            'location': (max_speed_row.get('GPS_LATITUDE', 'Not available'), max_speed_row.get('GPS_LONGITUDE', 'Not available')),
            'vehicle_id': max_speed_row['VEHICLE_ID']
        }


fastest_trip = max(mean_speeds, key=mean_speeds.get)
fastest_vehicle, fastest_trip_id = fastest_trip
fastest_mean_speed = mean_speeds[fastest_trip]

print("Maximum Speed:", max_speed, "m/s")
print("Maximum Speed Details:", max_speed_details)
print(f"The fastest average speed was {fastest_mean_speed:.2f} m/s by vehicle {fastest_vehicle} on trip {fastest_trip_id}.")

Maximum Speed: 200.33333333333334 m/s
Maximum Speed Details: {'time': Timestamp('2023-02-15 18:05:38'), 'location': (45.509918, -122.879553), 'vehicle_id': 3244}
The fastest average speed was 22.07 m/s by vehicle 3419 on trip 258614729.